import type { NextPage } from 'next';
import Head from 'next/head';
import { supabase } from 'utils/supabaseClient';
import Auth from 'components/supabase/Auth';
import Account from 'components/supabase/Account';
import styles from '/styles/Home.module.css';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
    const [session, setSession] = useState(null);

    useEffect(() => {
        setSession(supabase.auth.session());

        supabase.auth.onAuthStateChange((_event, session) => {
            setSession(session);
        });
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>Base supabase nextJS app</h1>

                <p>put some stuff here</p>
                {!session ? <Auth /> : <Account key={session.user.id} session={session} />}
            </main>

            <footer className={styles.footer}>
                <p>Capsule Corp.</p>
            </footer>
        </div>
    )
}

export default Home;
